insert into cozinha (nome) values ('cozinha 1');
insert into cozinha (nome) values ('cozinha 2');
insert into cozinha (nome) values ('cozinha 3');
insert into cozinha (nome) values ('cozinha 4');
insert into restaurante(nome, taxa_frete, cozinha_id, ativo, aberto, data_cadastro, data_atualizacao) values ('Tailzandeza',23.5,1, true, true,'2020-12-12','2020-12-12');
insert into restaurante(nome, taxa_frete, cozinha_id, ativo, aberto, data_cadastro, data_atualizacao) values ('Mexicana',3.5,2, true, true,'2020-12-12','2020-12-12');
insert into restaurante(nome, taxa_frete, cozinha_id, ativo, aberto, data_cadastro, data_atualizacao) values ('Espanhola',5.0,3, true, true,'2020-12-12','2020-12-12');
insert into restaurante(nome, taxa_frete, cozinha_id, ativo, aberto, data_cadastro, data_atualizacao) values ('Americana',3.5,4, true, true,'2020-12-12','2020-12-12');
insert into estado (nome, sigla) values ('Mato grosso do sul','MS');
insert into estado (nome, sigla) values ('Mato grosso','MT');
insert into estado (nome, sigla) values ('São Paulo','SP');
insert into estado (nome, sigla) values ('Rio de Janeiro','RJ');
insert into cidade (nome, estado_id) values ('Campo Grande',1);
insert into cidade (nome, estado_id) values ('Dourados',1);
insert into cidade (nome, estado_id) values ('Ribas do rio Pardo',1);
insert into cidade (nome, estado_id) values ('Cuiaba',2);
insert into cidade (nome, estado_id) values ('Sinopi',2);
insert into cidade (nome, estado_id) values ('Barras do Garça',2);
insert into cidade (nome, estado_id) values ('Valinhos',3);
insert into cidade (nome, estado_id) values ('Campina',3);
insert into cidade (nome, estado_id) values ('Niteroi',4);
insert into cidade (nome, estado_id) values ('Queimados',4);
insert into cidade (nome, estado_id) values ('Rio das Ostras',4);
insert into cidade (nome, estado_id) values ('Macaé',4);